version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: group_db
      POSTGRES_USER: group_db_user
      POSTGRES_PASSWORD: group_db_password
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
